apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: dynakube
    patch: |-
      - op: replace
        path: /metedata/name
        value: my-cluster
